"""Non-learning correctness baseline (correction plan Phase 4).

Multi-start constrained optimization on the canonical proxy:
objective = max(0, constraint residuals) summed lexicographically-first,
with a small secondary power term so feasible designs are also frugal.

This baseline exists so the learned models have something to beat. If a
neural model cannot beat multi-start DE + verification, it should not be
deployed (docs/codex_plan.md, gate G4). The dataset builder (Phase 3) reuses
the same objective for DE polish and infeasibility certification, so the
baseline and the training data are generated by one canonical implementation.
"""

from __future__ import annotations

import time

import numpy as np
from scipy.optimize import differential_evolution

from .. import config
from ..circuit.ota5t import InvalidDesignError
from ..devices.lut import DomainError
from ..evaluation.constraints import evaluate_constraints
from ..evaluation.evaluator import evaluate_design


def make_objective(ota, specs, cl):
    def objective(x):
        try:
            perf = ota.evaluate(x, CL=cl)
        except (InvalidDesignError, DomainError, ValueError, FloatingPointError):
            return 1e3  # finite, distinctly worse than any feasible design
        constraints, verdict = evaluate_constraints(perf, specs)
        violation = sum(max(0.0, c.residual) for c in constraints)
        secondary = perf["Power"] / config.OBS_POWER_NORM  # frugality, tiny weight
        return violation + 1e-3 * secondary
    return objective


def optimize_specs(ota, specs, seed=0, maxiter=60, popsize=20, n_starts=2):
    cl = float(specs.get("CL_pF", 1.0)) * 1e-12
    objective = make_objective(ota, specs, cl)
    best, best_val = None, np.inf
    t0 = time.time()
    n_evals = 0
    for k in range(n_starts):
        res = differential_evolution(
            objective, config.DESIGN_BOUNDS,
            seed=seed + k, maxiter=maxiter, popsize=popsize,
            mutation=(0.5, 1.0), recombination=0.7, tol=1e-6, polish=True,
        )
        n_evals += res.nfev
        if res.fun < best_val:
            best_val, best = float(res.fun), res.x
    runtime = time.time() - t0
    record = evaluate_design(ota, best, specs)
    record["baseline"] = {
        "method": "differential_evolution",
        "objective": best_val, "n_evals": int(n_evals),
        "runtime_s": round(runtime, 1), "seeds": [seed, seed + n_starts - 1],
    }
    return record
