"""OCEAN measurement script generation for correlation jobs."""

from __future__ import annotations


def render_measurement_script(case_id: str, vdd: float = 1.2) -> str:
    """Return an IC617-compatible OCEAN script.

    The first campaign smoke test validates PSF signal names. Node and AC
    measurements use public saved signals. Device OP extraction is deferred
    until smoke-test diagnostics reveal MMSIM14's exact names.
    """
    return f'''/* Generated by analog_ai for {case_id}. */
openResults("./psf")
printf("ANALOG_AI_RESULTS_BEGIN\\n")
printf("%L\\n" results())
printf("ANALOG_AI_RESULTS_END\\n")

selectResult('ac)
printf("ANALOG_AI_AC_OUTPUTS_BEGIN\\n")
printf("%L\\n" outputs())
printf("ANALOG_AI_AC_OUTPUTS_END\\n")
gain = v("Vout") / (v("Vin+") - v("Vin-"))
gainDbWave = db20(gain)
phaseWave = phase(gain)
gainDb = value(gainDbWave 1.0)
ugf = cross(gainDbWave 0.0 1 "falling")
bw3 = cross(gainDbWave (gainDb - 3.0) 1 "falling")
phaseAtUgf = value(phaseWave ugf)
phaseMargin = 180.0 + phaseAtUgf

selectResult('dc)
printf("ANALOG_AI_DC_OUTPUTS_BEGIN\\n")
printf("%L\\n" outputs())
printf("ANALOG_AI_DC_OUTPUTS_END\\n")
voutDc = v("Vout")
vtailDc = v("net02")
vmirrorDc = v("net04")
vddCurrent = i("V4:p")
powerDc = {float(vdd):.12g} * abs(vddCurrent)

/* stdout is captured by the guest runner. Avoid OCEAN-side file output
 * because this old IC617 build does not reliably write on VMware hgfs. */
printf("ANALOG_AI_METRICS %.15g %.15g %.15g %.15g %.15g %.15g %.15g %.15g %.15g %.15g\\n"
       gainDb bw3 ugf phaseAtUgf phaseMargin voutDc vtailDc vmirrorDc
       vddCurrent powerDc)
exit()
'''
